### ISSUE TITLE
"Multiplicity" in scheme 

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/FinGreyLit#4]
In the [data scheme of this repo](https://github.com/NatLibFi/FinGreyLit/blob/main/schema.md) there could be a column indicating whether the field is allowed to have only a single value or multiple values.

**Comment by osma** [comment]
Good idea. It's already stated in the [metadata coverage table](https://github.com/NatLibFi/FinGreyLit/blob/main/statistics.md#metadata-coverage-by-document-type), but the schema documentation would be a more obvious place for this information.
